[0m19:46:32.210523 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D0C01520C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D0C01519A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D0C08C27E0>]}


============================== 19:46:32.382391 | 159bfe35-3895-4ead-998a-b1c109d402e9 ==============================
[0m19:46:32.382391 [info ] [MainThread]: Running with dbt=1.9.2
[0m19:46:32.382391 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\gtaye\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt init ethiomed', 'send_anonymous_usage_stats': 'True'}
[0m19:46:36.083754 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'WindowsPath'.. Dictionary: {'dir': WindowsPath('C:/Users/gtaye/.dbt')}
[0m19:46:36.083754 [info ] [MainThread]: Creating dbt configuration folder at 
[0m19:46:36.209359 [debug] [MainThread]: Starter project path: C:\Users\gtaye\AppData\Local\anaconda3\Lib\site-packages\dbt\include\starter_project
[0m19:46:36.280168 [info ] [MainThread]: 
Your new dbt project "ethiomed" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m19:46:36.280168 [info ] [MainThread]: Setting up your profile.
[0m19:54:16.724325 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000202532D0B30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002024DBADBB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020253CF1A60>]}


============================== 19:54:16.724325 | 275ee9f2-3ee9-48db-bfbf-8d02d6f3851e ==============================
[0m19:54:16.724325 [info ] [MainThread]: Running with dbt=1.9.2
[0m19:54:16.724325 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\gtaye\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt init ethiomed', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:54:16.810902 [info ] [MainThread]: A project called ethiomed already exists here.
[0m19:54:16.854104 [debug] [MainThread]: Command `dbt init` succeeded at 19:54:16.810902 after 0.39 seconds
[0m19:54:16.854104 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020253249550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002025387B0E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002025387A540>]}
[0m19:54:16.859483 [debug] [MainThread]: Flushing usage events
[0m19:54:18.339450 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:56:01.398051 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CE7265D940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CE6FBBDC10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CE7231B680>]}


============================== 19:56:01.413677 | 192dd2e8-943d-48f5-8e11-f14ee1b31838 ==============================
[0m19:56:01.413677 [info ] [MainThread]: Running with dbt=1.9.2
[0m19:56:01.413677 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\gtaye\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init ethiomedi', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m19:56:01.507648 [debug] [MainThread]: Starter project path: C:\Users\gtaye\AppData\Local\anaconda3\Lib\site-packages\dbt\include\starter_project
[0m19:56:01.679513 [info ] [MainThread]: 
Your new dbt project "ethiomedi" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m19:56:01.679513 [info ] [MainThread]: Setting up your profile.
[0m19:58:02.170888 [info ] [MainThread]: Profile ethiomedi written to C:\Users\gtaye\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m19:58:02.176155 [debug] [MainThread]: Command `dbt init` succeeded at 19:58:02.176155 after 121.87 seconds
[0m19:58:02.176155 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CE72F02270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CE72E83EC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CE72F55AF0>]}
[0m19:58:02.176155 [debug] [MainThread]: Flushing usage events
[0m19:58:03.985597 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m20:13:04.760279 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D52D343080>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D52D343290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D52D341100>]}


============================== 20:13:04.943466 | 758cbe49-7fcd-46a0-8463-39301f2c2940 ==============================
[0m20:13:04.943466 [info ] [MainThread]: Running with dbt=1.9.2
[0m20:13:04.948463 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\gtaye\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m20:13:08.155638 [info ] [MainThread]: dbt version: 1.9.2
[0m20:13:08.162631 [info ] [MainThread]: python version: 3.12.3
[0m20:13:08.168629 [info ] [MainThread]: python path: C:\Users\gtaye\AppData\Local\anaconda3\python.exe
[0m20:13:08.174660 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m20:13:09.234460 [info ] [MainThread]: Using profiles dir at C:\Users\gtaye\.dbt
[0m20:13:09.235459 [info ] [MainThread]: Using profiles.yml file at C:\Users\gtaye\.dbt\profiles.yml
[0m20:13:09.238459 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\gtaye\Documents\10Acadamy\week7\dbt_project.yml
[0m20:13:09.245455 [info ] [MainThread]: adapter type: postgres
[0m20:13:09.248457 [info ] [MainThread]: adapter version: 1.9.0
[0m20:13:09.250454 [info ] [MainThread]: Configuration:
[0m20:13:09.253455 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m20:13:09.256452 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m20:13:09.260446 [info ] [MainThread]: Required dependencies:
[0m20:13:09.263445 [debug] [MainThread]: Executing "git --help"
[0m20:13:09.622237 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m20:13:09.624237 [debug] [MainThread]: STDERR: "b''"
[0m20:13:09.627235 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m20:13:09.629233 [info ] [MainThread]: Connection:
[0m20:13:09.631234 [info ] [MainThread]:   host: localhost
[0m20:13:09.633231 [info ] [MainThread]:   port: 5432
[0m20:13:09.635230 [info ] [MainThread]:   user: postgres
[0m20:13:09.637229 [info ] [MainThread]:   database: data_warehouse
[0m20:13:09.639229 [info ] [MainThread]:   schema: schemas(1)
[0m20:13:09.642226 [info ] [MainThread]:   connect_timeout: 10
[0m20:13:09.646224 [info ] [MainThread]:   role: None
[0m20:13:09.649222 [info ] [MainThread]:   search_path: None
[0m20:13:09.650221 [info ] [MainThread]:   keepalives_idle: 0
[0m20:13:09.652220 [info ] [MainThread]:   sslmode: None
[0m20:13:09.654220 [info ] [MainThread]:   sslcert: None
[0m20:13:09.657219 [info ] [MainThread]:   sslkey: None
[0m20:13:09.660216 [info ] [MainThread]:   sslrootcert: None
[0m20:13:09.662215 [info ] [MainThread]:   application_name: dbt
[0m20:13:09.664216 [info ] [MainThread]:   retries: 1
[0m20:13:09.671211 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m20:13:11.025433 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m20:13:15.875928 [debug] [MainThread]: Using postgres connection "debug"
[0m20:13:15.876911 [debug] [MainThread]: On debug: select 1 as id
[0m20:13:15.878910 [debug] [MainThread]: Opening a new connection, currently in state init
[0m20:13:17.092915 [debug] [MainThread]: Postgres adapter: Got a retryable error when attempting to open a postgres connection.
1 attempts remaining. Retrying in 0 seconds.
Error:
connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

[0m20:13:17.502855 [debug] [MainThread]: Postgres adapter: Error running SQL: select 1 as id
[0m20:13:17.504855 [debug] [MainThread]: Postgres adapter: Rolling back transaction.
[0m20:13:17.506854 [debug] [MainThread]: On debug: No close available on handle
[0m20:13:17.508852 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m20:13:17.510851 [info ] [MainThread]: [31m2 checks failed:[0m
[0m20:13:17.511850 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\gtaye\Documents\10Acadamy\week7\dbt_project.yml> not found

[0m20:13:17.513871 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
  

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m20:13:17.564819 [debug] [MainThread]: Command `dbt debug` failed at 20:13:17.519847 after 13.47 seconds
[0m20:13:17.566820 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m20:13:17.568819 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D52D6B0A70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D52D3E2CC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D52EEAC800>]}
[0m20:13:17.569819 [debug] [MainThread]: Flushing usage events
[0m20:13:19.650134 [debug] [MainThread]: An error was encountered while trying to flush usage events
